### ISSUE TITLE
Create a new element for state drop down list

### ISSUE THREAD

**Issue by cherukumilli** [biztek/usa-state-list#1]
- [x]  use the following URL as a reference to create a state drop down list that will include states, outlying territories, armed forces
  - http://www.freeformatter.com/usa-state-list-html-select.html
- [x] the element should adhere to the material design guidelines
- [x] update `pmp-ui (in places like pmp-account-organization)` with this element and replace current occurrences of hardcoded paper-dropdown with this element

**Comment by sricharan123** [comment]
@cherukumilli 
fixed.
