### ISSUE TITLE
Render blocking code in your attached() callback

### ISSUE THREAD

**Issue by cherukumilli** [biztek/usa-state-list#2]
code inside attached callback is render blocking. i.e., it will stop the UI from painting and the UI will behave slowly when it starts up.

Please surround the following code in an async call:
```
        this._loadJSON('states.json');
```

**Comment by cherukumilli** [comment]
@sricharan123 
There is no reference to the pull request here. Please make sure this issue is properly closed.

**Comment by sricharan123** [comment]
issue 385 closed issue.
