### ISSUE TITLE
usa-state-list is featured in a Vaadin blog

### ISSUE THREAD

**Issue by binbalenci** [biztek/usa-state-list#23]
Hi biztek,

Recently, I wrote the article [Dropdown components with ready-to-use data](https://vaadin.com/blog/wcw-22-dropdown-components) with your component featured in it. I believe your component is very useful and thus, I want to introduce it to people.

Feel free to drop a comment down below and have a nice day!

Regards,
Binh

**Comment by cherukumilli** [comment]
@binhbbbb 
Thanks @binhbbbb .
BTW: `Vaadin` used to be located in the same office as `Biztek` in San Jose, CA (before they moved to Sunnyvale). Great to see Vaadin doing amazing work.

**Comment by binbalenci** [comment]
That's nice to hear. I did not know that information before. And thanks for the compliment 😉 All the best wishes to you and your company too.

P/s: Can I add the badges to your other components too? They look great and with the badges, it induces more users to see those.

**Comment by cherukumilli** [comment]
@binhbbbb The components need some work :( but pls feel free to add the badges.
