### ISSUE TITLE
Correct documentation in README.md

### ISSUE THREAD

**Issue by cherukumilli** [biztek/usa-state-list#7]
A cursory glance of the README.md file shows the following problems:
- [x] `h2` heading messed up because of no space after ##
  - `##<usa-state-list>`

- [x] The following sentence should start with an uppercase letter
  - `state drop down list that will include states`

- [x] There is no space after comma in the following sentence
  - `It includes an optional label,error message,invalid,autovalidate`

- [x] Incorrect bower install command
  - `$ bower install — save biztek/usa-state-list`

- [x] Incorrect initial push request. The following should be corrected
 - from: `git push origin usa-state-list`
 - to: `git push -u origin usa-state-list`

- [x] Remove :D at the end of `Submit a pull request :D`

**Comment by anushagadepalli** [comment]
@cherukumilli 
I updated the README.md file, please review my changes.
